-- Table: public.hw_assignment_data

-- DROP TABLE IF EXISTS public.hw_assignment_data;

CREATE TABLE IF NOT EXISTS public.hw_assignment_data
(
    marketing_flag text COLLATE pg_catalog."default",
    primary_key_type text COLLATE pg_catalog."default",
    campaign_member_id text COLLATE pg_catalog."default",
    campaign_id text COLLATE pg_catalog."default",
    parent_channel text COLLATE pg_catalog."default",
    campaign_name text COLLATE pg_catalog."default",
    campaign_type text COLLATE pg_catalog."default",
    campaign_team text COLLATE pg_catalog."default",
    master_channel text COLLATE pg_catalog."default",
    source text COLLATE pg_catalog."default",
    contact_id text COLLATE pg_catalog."default",
    buyer_persona text COLLATE pg_catalog."default",
    account_id text COLLATE pg_catalog."default",
    account_name text COLLATE pg_catalog."default",
    industry text COLLATE pg_catalog."default",
    customer_type text COLLATE pg_catalog."default",
    opportunity_type text COLLATE pg_catalog."default",
    lead_segment text COLLATE pg_catalog."default",
    oppty_segment text COLLATE pg_catalog."default",
    ai_model_industry_archetype text COLLATE pg_catalog."default",
    ai_model_primary_industry text COLLATE pg_catalog."default",
    ai_model_secondary_industry text COLLATE pg_catalog."default",
    is_renewal boolean,
    lead_region text COLLATE pg_catalog."default",
    oppty_region text COLLATE pg_catalog."default",
    lead_sector text COLLATE pg_catalog."default",
    account_sector text COLLATE pg_catalog."default",
    tier_w_suppression text COLLATE pg_catalog."default",
    campaign_interaction_date date,
    lead_team text COLLATE pg_catalog."default",
    owner_role_grouping text COLLATE pg_catalog."default",
    team text COLLATE pg_catalog."default",
    campaign_date date,
    campaign_week text COLLATE pg_catalog."default",
    campaign_month text COLLATE pg_catalog."default",
    campaign_quarter text COLLATE pg_catalog."default",
    campaign_year text COLLATE pg_catalog."default",
    lead_date date,
    lead_week text COLLATE pg_catalog."default",
    lead_month text COLLATE pg_catalog."default",
    lead_quarter text COLLATE pg_catalog."default",
    lead_year text COLLATE pg_catalog."default",
    mql_date date,
    mql_week text COLLATE pg_catalog."default",
    mql_month text COLLATE pg_catalog."default",
    mql_quarter text COLLATE pg_catalog."default",
    mql_year text COLLATE pg_catalog."default",
    sal_date date,
    sal_week text COLLATE pg_catalog."default",
    sal_month text COLLATE pg_catalog."default",
    sal_quarter text COLLATE pg_catalog."default",
    sal_year text COLLATE pg_catalog."default",
    is_faulty_lead boolean,
    is_small_fleet boolean,
    touchpoint_timestamp timestamp with time zone,
    touchpoint_week text COLLATE pg_catalog."default",
    touchpoint_month text COLLATE pg_catalog."default",
    touchpoint_quarter text COLLATE pg_catalog."default",
    touchpoint_year text COLLATE pg_catalog."default",
    touchpoint_id text COLLATE pg_catalog."default",
    touchpoint_name text COLLATE pg_catalog."default",
    opportunity_id text COLLATE pg_catalog."default",
    opportunity_name text COLLATE pg_catalog."default",
    opportunity_stage text COLLATE pg_catalog."default",
    opp_stage_group text COLLATE pg_catalog."default",
    is_webstore_upsell_opportunity boolean,
    product_line_grouping text COLLATE pg_catalog."default",
    product_line text COLLATE pg_catalog."default",
    percent_of_total double precision,
    op_created_date date,
    op_created_week text COLLATE pg_catalog."default",
    op_created_month text COLLATE pg_catalog."default",
    op_created_quarter text COLLATE pg_catalog."default",
    op_created_year text COLLATE pg_catalog."default",
    sqo_date date,
    sqo_week text COLLATE pg_catalog."default",
    sqo_month text COLLATE pg_catalog."default",
    sqo_quarter text COLLATE pg_catalog."default",
    sqo_year text COLLATE pg_catalog."default",
    op_closed_date date,
    op_closed_week text COLLATE pg_catalog."default",
    op_closed_month text COLLATE pg_catalog."default",
    op_closed_quarter text COLLATE pg_catalog."default",
    op_closed_year text COLLATE pg_catalog."default",
    locr_oppty_flag text COLLATE pg_catalog."default",
    locr_60_oppty_flag text COLLATE pg_catalog."default",
    locr_15_oppty_flag text COLLATE pg_catalog."default",
    locr_0_oppty_flag text COLLATE pg_catalog."default",
    sql double precision,
    sql_pipe double precision,
    total_opp_value double precision,
    sql_deal_progression double precision,
    sqo double precision,
    closed_won double precision,
    closed_lost double precision,
    closed_won_pipe double precision,
    closed_lost_pipe double precision
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.hw_assignment_data
    OWNER to postgres;